[package]
name = "authenticator"
version = "0.1.0"
edition = "2024"

[dependencies]
logging = { path = "../logging" }
config = { path = "../config" }
database = { path = "../database" }
cache = { path = "../cache" }
reqwest = { version = "0.12", features = ["json"] }
jsonwebtoken = { version = "10", features = ["aws_lc_rs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
async-trait = "0"
uuid = "1"
tokio = "1"
sha2 = "0"
oauth2 = { version = "5", default-features = false, features = ["reqwest", "rustls-tls"] }

[dev-dependencies]
chrono = "0.4.45"
libtest-mimic = "0.8.2"
serde_json = "1"
testcontainers = "0.24"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }

[[test]]
name = "keycloak"
harness = false
