---
include:
  - infrastructure/docker-compose/docker-compose.base.yml
  - infrastructure/docker-compose/docker-compose.monitoring.yml
  - infrastructure/docker-compose/docker-compose.debug-services.yml
  - infrastructure/docker-compose/docker-compose.authentication.yml
  - infrastructure/docker-compose/docker-compose.release.yml
  - infrastructure/docker-compose/docker-compose.debug.yml
