/// Router file.
///
/// This file regroups all the available routes from the API and organizes them.
/// Also adds the middleware layer and defines private routes such as Prometheus /metrics.
///
/// To add a new route, define it using utoipa decorator and specify:
/// - its documentation
/// - its method
/// - its path
/// - its responses examples
///
/// For example:
///
/// ```rs
/// /// Health Check of the API
/// #[utoipa::path(
///     get,
///     path = "/",
///     responses(
///         (status = OK, description = "The API is up and running."),
///     ),
/// )]
/// pub(crate) async fn health_check() -> &'static str {
///     ""
/// }
/// ```
///
/// Then import it as follows, with its `__path_` that is generated by utoipa:
///
/// ```rs
/// use crate::misc::{health_check, __path_health_check};
/// ```
///
/// Finally, add the route to the OpenApiRouter:
///
/// ```rs
/// .routes(routes!(health_check))
/// ```
use crate::misc::{__path_health_check, health_check};
use axum::{Router, routing::get};

use crate::middleware::middleware_layer;
use axum::http::header::AUTHORIZATION;
use axum::http::{Request, StatusCode};
use axum::routing::Route;
use axum_prometheus::metrics_exporter_prometheus::PrometheusHandle;
use config::Config;
use std::future::ready;
use std::iter::once;
use std::time::Duration;
use tower::layer::Layer;
use tower::layer::util::Stack;
use tower::{Service, ServiceBuilder};
use tower_http::{
    CompressionLevel,
    compression::CompressionLayer,
    cors::CorsLayer,
    decompression::RequestDecompressionLayer,
    normalize_path::NormalizePathLayer,
    sensitive_headers::{
        SetSensitiveRequestHeadersLayer, SetSensitiveResponseHeadersLayer,
    },
    timeout::TimeoutLayer,
    trace::TraceLayer,
};
use utoipa::openapi::{InfoBuilder, OpenApi};
use utoipa_axum::{router::OpenApiRouter, routes};
use utoipa_swagger_ui::SwaggerUi;

//TODO: Put this in the config

// Bookmark this: https://docs.rs/axum/latest/axum/routing/struct.Router.html

/// Public routes that qre exposed to the world
// pub(crate) fn public_routes(config: &Config, storage: Arc<Rwlock<Storage>>, core: Arc<Rwlock<Core>>) -> (Router, OpenApi) {
pub fn public_routes(config: &Config) -> Router {
    let (api_routes, openapi) = OpenApiRouter::new()
        .routes(routes!(health_check))
        .split_for_parts();

    let api_routes = api_routes.merge(swagger(config, openapi));

    let middleware = ServiceBuilder::new()
        // Avoid logging these headers content
        .layer(SetSensitiveRequestHeadersLayer::new(once(AUTHORIZATION)))
        .layer(SetSensitiveResponseHeadersLayer::new(once(AUTHORIZATION)))
        .layer(TraceLayer::new_for_http())
        // Authorize OPTIONS requests for CORS and automatically set up headers
        //TODO: Set this up based on what is actually available
        .layer(CorsLayer::permissive())
        .layer(NormalizePathLayer::trim_trailing_slash())
        .layer(CompressionLayer::new().quality(CompressionLevel::Best))
        .layer(RequestDecompressionLayer::new())
        .layer(TimeoutLayer::with_status_code(
            StatusCode::REQUEST_TIMEOUT,
            Duration::from_secs(config.api.timeout_sec.into()),
        ));

    let router = api_routes.layer(middleware).with_state(config.clone());

    router
}

/// Swagger UI and OpenAPI routes layer.
fn swagger(config: &Config, openapi: OpenApi) -> SwaggerUi {
    let swagger_config = config.swagger.as_ref().unwrap().clone();
    let swagger_ui_path = swagger_config.swagger_ui_path;
    let openapi_path = swagger_config.openapi_path;
    let mut openapi = openapi;
    openapi.info = InfoBuilder::new()
        .title(env!("CARGO_PKG_NAME"))
        .description(option_env!("CARGO_PKG_DESCRIPTION"))
        .version(env!("CARGO_PKG_VERSION"))
        .build();
    SwaggerUi::new(swagger_ui_path).url(openapi_path, openapi)
}

/// Metrics routes that are exposed to Prometheus
pub fn try_metrics_routes(
    metric_handle: PrometheusHandle,
) -> Result<Router, anyhow::Error> {
    Ok(Router::new().route("/metrics", get(move || ready(metric_handle.render()))))
}
