/// Router file.
///
/// This file regroups all the available routes from the API and organizes them.
/// Also adds the middleware layer and defines private routes such as Prometheus /metrics.
///
/// To add a new route, define it using utoipa decorator and specify:
/// - its documentation
/// - its method
/// - its path
/// - its responses examples
///
/// For example:
///
/// ```rs
/// /// Health Check of the API
/// #[utoipa::path(
///     get,
///     path = "/",
///     responses(
///         (status = OK, description = "The API is up and running."),
///     ),
/// )]
/// pub(crate) async fn health_check() -> &'static str {
///     ""
/// }
/// ```
///
/// Then import it as follows, with its `__path_` that is generated by utoipa:
///
/// ```rs
/// use crate::misc::{health_check, __path_health_check};
/// ```
///
/// Finally, add the route to the OpenApiRouter:
///
/// ```rs
/// .routes(routes!(health_check))
/// ```
use crate::{
    app_state::AppState,
    endpoints::{
        api_key::endpoints::{
            __path_create_api_key, __path_delete_api_key, __path_get_api_key,
            create_api_key, delete_api_key, get_api_key,
        },
        ping::endpoints::{__path_ping, ping},
        storage::endpoints::{
            __path_delete_stored_file, __path_download, __path_upload,
            delete_stored_file, download, upload,
        },
        user::endpoints::{__path_get_user, get_user},
    },
};
use crate::observability::{MakeRequestUuidV7, make_request_span};
use axum::{Router, routing::get};

use axum::http::StatusCode;
use axum::http::header::AUTHORIZATION;
use axum_prometheus::metrics_exporter_prometheus::PrometheusHandle;
use config::Config;
use std::future::ready;
use std::iter::once;
use std::time::Duration;
use tower::ServiceBuilder;
use tower_http::{
    CompressionLevel,
    compression::CompressionLayer,
    cors::CorsLayer,
    decompression::RequestDecompressionLayer,
    normalize_path::NormalizePathLayer,
    request_id::{PropagateRequestIdLayer, SetRequestIdLayer},
    sensitive_headers::{
        SetSensitiveRequestHeadersLayer, SetSensitiveResponseHeadersLayer,
    },
    timeout::TimeoutLayer,
    trace::TraceLayer,
};
use utoipa::openapi::{InfoBuilder, OpenApi};
use utoipa_axum::{router::OpenApiRouter, routes};
use utoipa_swagger_ui::SwaggerUi;

// Bookmark this: https://docs.rs/axum/latest/axum/routing/struct.Router.html

/// Builds the [`OpenApiRouter`] holding every public API route.
///
/// This only assembles the route definitions and their generated schemas, so it
/// can be called without any running service (database, cache, storage, ...).
/// It is the single source of truth shared by [`public_routes`] and [`openapi`].
fn api_router() -> OpenApiRouter<AppState> {
    OpenApiRouter::<AppState>::new()
        .routes(routes!(ping))
        .routes(routes!(upload))
        .routes(routes!(download))
        .routes(routes!(delete_stored_file))
        .routes(routes!(get_user))
        .routes(routes!(create_api_key))
        .routes(routes!(get_api_key))
        .routes(routes!(delete_api_key))
}

/// Metadata advertised in the generated OpenAPI document.
fn api_info() -> utoipa::openapi::Info {
    InfoBuilder::new()
        .title(env!("CARGO_PKG_NAME"))
        .description(option_env!("CARGO_PKG_DESCRIPTION"))
        .version(env!("CARGO_PKG_VERSION"))
        .build()
}

/// Builds the OpenAPI document describing the public API.
///
/// Requires no running service, so it can be serialized offline (e.g. to
/// generate the frontend API types).
pub fn openapi() -> OpenApi {
    let (_, mut openapi) = api_router().split_for_parts();
    openapi.info = api_info();
    openapi
}

/// Public routes that qre exposed to the world
pub fn public_routes(config: &Config, state: AppState) -> Router {
    let (api_routes, openapi) = api_router().split_for_parts();

    let api_routes = api_routes.merge(swagger(config, openapi));

    let middleware = ServiceBuilder::new()
        // Avoid logging these headers content
        .layer(SetSensitiveRequestHeadersLayer::new(once(AUTHORIZATION)))
        // Reuse an inbound x-request-id or mint a fresh UUID v7. Must run before
        // the trace layer so the span can read the id from the request headers.
        .layer(SetRequestIdLayer::x_request_id(MakeRequestUuidV7))
        // Scope every event of the request under a span carrying the request_id
        .layer(TraceLayer::new_for_http().make_span_with(make_request_span))
        // Echo the request id back to the client in the response headers
        .layer(PropagateRequestIdLayer::x_request_id())
        .layer(SetSensitiveResponseHeadersLayer::new(once(AUTHORIZATION)))
        // Authorize OPTIONS requests for CORS and automatically set up headers
        //TODO: Set this up based on what is actually available
        .layer(CorsLayer::permissive())
        .layer(NormalizePathLayer::trim_trailing_slash())
        .layer(CompressionLayer::new().quality(CompressionLevel::Best))
        .layer(RequestDecompressionLayer::new())
        .layer(TimeoutLayer::with_status_code(
            StatusCode::REQUEST_TIMEOUT,
            Duration::from_secs(config.api.timeout_sec.into()),
        ));

    api_routes.layer(middleware).with_state(state)
}

/// Swagger UI and OpenAPI routes layer.
fn swagger(config: &Config, openapi: OpenApi) -> SwaggerUi {
    let swagger_config = config.swagger.as_ref().unwrap().clone();
    let swagger_ui_path = swagger_config.swagger_ui_path;
    let openapi_path = swagger_config.openapi_path;
    let mut openapi = openapi;
    openapi.info = api_info();
    SwaggerUi::new(swagger_ui_path).url(openapi_path, openapi)
}

/// Metrics routes that are exposed to Prometheus
pub fn try_metrics_routes(
    path: &str,
    metric_handle: PrometheusHandle,
) -> Result<Router, anyhow::Error> {
    Ok(Router::new().route(path, get(move || ready(metric_handle.render()))))
}
