/// Router file.
///
/// This file regroups all the available routes from the API and organizes them.
/// Also adds the middleware layer and defines private routes such as Prometheus /metrics.
///
/// To add a new route, define it using utoipa decorator and specify:
/// - its documentation
/// - its method
/// - its path
/// - its responses examples
///
/// For example:
///
/// ```rs
/// /// Health Check of the API
/// #[utoipa::path(
///     get,
///     path = "/",
///     responses(
///         (status = OK, description = "The API is up and running."),
///     ),
/// )]
/// pub(crate) async fn health_check() -> &'static str {
///     ""
/// }
/// ```
///
/// Then import it as follows, with its `__path_` that is generated by utoipa:
///
/// ```rs
/// use crate::misc::{health_check, __path_health_check};
/// ```
///
/// Finally, add the route to the OpenApiRouter:
///
/// ```rs
/// .routes(routes!(health_check))
/// ```
use crate::misc::{__path_health_check, health_check};
use axum::{Router, routing::get};

use crate::middleware::middleware_layer;
use axum_prometheus::metrics_exporter_prometheus::PrometheusHandle;
use config::Config;
use std::future::ready;
use utoipa::openapi::{InfoBuilder, OpenApi};
use utoipa_axum::{router::OpenApiRouter, routes};
use utoipa_swagger_ui::SwaggerUi;

//TODO: Put this in the config

// Bookmark this: https://docs.rs/axum/latest/axum/routing/struct.Router.html

/// Public routes that qre exposed to the world
// pub(crate) fn public_routes(config: &Config, storage: Arc<Rwlock<Storage>>, core: Arc<Rwlock<Core>>) -> (Router, OpenApi) {
pub(crate) fn public_routes(config: &Config) -> (Router, OpenApi) {
    let middleware_service = middleware_layer(config);
    let (api_routes, openapi) = OpenApiRouter::new()
        .routes(routes!(health_check))
        .split_for_parts();
    api_routes.merge(swagger(config, openapi));

    let router = api_routes.layer(middleware_service).with_state(config);

    (router, openapi)
}

/// Swagger UI and OpenAPI routes layer.
fn swagger(config: &Config, openapi: OpenApi) -> SwaggerUi {
    let swagger_config = config.swagger.as_ref().unwrap().clone();
    let swagger_ui_path = swagger_config.swagger_ui_path;
    let openapi_path = swagger_config.openapi_path;
    let mut openapi = openapi;
    openapi.info = InfoBuilder::new()
        .title(env!("CARGO_PKG_NAME"))
        .description(option_env!("CARGO_PKG_DESCRIPTION"))
        .version(env!("CARGO_PKG_VERSION"))
        .build();
    SwaggerUi::new(swagger_ui_path).url(openapi_path, openapi)
}

/// Metrics routes that are exposed to Prometheus
pub(crate) fn try_metrics_routes(
    metric_handle: PrometheusHandle,
) -> Result<Router, anyhow::Error> {
    Ok(Router::new().route("/metrics", get(move || ready(metric_handle.render()))))
}
