# This configuration is for development purposes only and needs
# many security enhancement before going to production.
scrape_configs:
  - job_name: node
    scheme: "http"
    static_configs:
      - targets: ["host.docker.internal:9100"]
  - job_name: backend
    scheme: "http"
    static_configs:
      - targets: ["backend:9100"]
  - job_name: frontend
    scheme: "http"
    static_configs:
      - targets: ["frontend:9100"]
  - job_name: postgres-exporter
    scheme: "http"
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: prometheus-self-monitoring
    scheme: "http"
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: grafana
    scheme: "http"
    static_configs:
      - targets: ["grafana:3000"]
