---
# This docker compose file is solely intended for development
# purposes and not for production use.
# Contains the base docker-compose.yml files, as well as hot-reloading
# frontend and backend.
#
# Run using --profile debug
#
services:
  backend-debug:
    image: localhost/app_backend:latest-debug
    build:
      context: ../..
      dockerfile: infrastructure/docker/app_backend/Dockerfile.debug
      tags:
        - "localhost/app_backend:latest-debug"
    depends_on:
      migrate:
          condition: service_completed_successfully
    container_name: app_backend
    env_file:
      - ${GIT_ROOT:-../..}/.env
    environment:
      IP: 0.0.0.0
      PORT: 9876
      PROMETHEUS_IP: 0.0.0.0
      PROMETHEUS_PORT: 9100
      SWAGGER_UI_PATH: "/v1/docs/swagger-ui"
      SWAGGER_OPENAPI_PATH: "/v1/docs/openapi.json"
      DEBUG: true
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DATABASE}
      DATABASE_USER: ${POSTGRES_READWRITE_USER}
      DATABASE_PASSWORD: ${POSTGRES_READWRITE_PASSWORD}
    networks:
      - net
    ports:
      - "${BACKEND_PORT}:9876"
    profiles: [debug]
    restart: on-failure
    volumes:
      - "${GIT_ROOT:-../..}/:/src"

  frontend-debug:
    image: localhost/app_frontend:latest-debug
    build:
      context: ../..
      dockerfile: infrastructure/docker/app_frontend/Dockerfile.debug
      tags:
        - "localhost/app_frontend:latest-debug"
    container_name: app_frontend
    environment:
      API_ROOT: ${API_ROOT}
    networks:
      - net
    ports:
      - "${FRONTEND_PORT}:8080"
    restart: on-failure
    profiles: [debug]
    volumes:
      - "${GIT_ROOT:-../..}/frontend:/src"

networks:
  net:
