---
# Contains services used to collect and expose metrics such as Prometheus.

services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    networks:
      - net
    ports:
      - "${PROMETHEUS_PORT}:9090"
    restart: on-failure
    profiles: [monitoring]
    volumes:
      - "prometheus:/prometheus"
      - ${GIT_ROOT:-../..}/infrastructure/prometheus:/etc/prometheus

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    networks:
      - net
    restart: on-failure
    profiles: [monitoring]
    environment:
      DATA_SOURCE_URI: "postgres:5432/postgres?sslmode=disable"
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    networks:
      - net
    profiles: [monitoring]
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: on-failure
    volumes:
      - "grafana:/var/lib/grafana"

networks:
  net:

volumes:
  prometheus:
