// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
    id: string
    createdAt: number
}

export type Entity<T> = {
    [K in keyof T]: T[K]
} & BaseEntity

export type Meta = {
    page: number
    total: number
    totalPages: number
}

// Auth identity returned by GET /auth/me (BFF — no JWT decoding in JS)
export type User = {
    id: string
    email: string | null
    role: 'ADMIN' | 'USER'
}

// Full application user record returned by GET /users and embedded in resources
export type AppUser = Entity<{
    firstName: string
    lastName: string
    email: string
    role: 'ADMIN' | 'USER'
    teamId: string
    bio: string
}>

export type Team = Entity<{
    name: string
    description: string
}>

export type Discussion = Entity<{
    title: string
    body: string
    teamId: string
    author: AppUser
}>

export type Comment = Entity<{
    body: string
    discussionId: string
    author: AppUser
}>
