FROM oven/bun:1.3.14

EXPOSE 8080
WORKDIR /src
VOLUME [ "/src" ]
USER bun

ENTRYPOINT [ "bun" ]
CMD [ \
    "vite", \
    "--debug", \
    "--host", "0.0.0.0", \
    "--port", "8080", \
    "--strictPort", \
    "--logLevel", "info" \
    ]
