/// Router module.
///
/// This module regroups all the available routes from the API and organizes them.
/// Also adds the middleware layer and defines private routes such as Prometheus /metrics.
///
/// To add a new route, define it using utoipa decorator and specify:
/// - its documentation
/// - its method
/// - its path
/// - its responses examples
///
/// For example:
///
/// ```rs
/// /// Health Check of the API
/// #[utoipa::path(
///     get,
///     path = "/",
///     responses(
///         (status = OK, description = "The API is up and running."),
///     ),
/// )]
/// pub(crate) async fn health_check() -> &'static str {
///     ""
/// }
/// ```
///
/// Then import it as follows, with its `__path_` that is generated by utoipa:
///
/// ```rs
/// use crate::misc::{health_check, __path_health_check};
/// ```
///
/// Finally, add the route to the OpenApiRouter:
///
/// ```rs
/// .routes(routes!(health_check))
/// ```
mod middlewares;
mod observability;
mod openapi;
mod router;

pub use openapi::openapi;
pub use router::{public_routes, try_metrics_routes};
