---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fullstack-rust-react-template
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
