---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fullstack-rust-react-template
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9876
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
    - name: swagger
      port: 7070
      targetPort: swagger
      protocol: TCP
  selector:
    app.kubernetes.io/name: backend
