#!/usr/bin/env bash
set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_ROOT"

# .agents/skills/api-* is generated by openapi2skill, so it is not linted.
MARKDOWN_FILES=$(git ls-files "*.md" | grep -v "^\.agents/skills/api-")

markdownlint $MARKDOWN_FILES -c "$GIT_ROOT/.markdownlint.json"

# The config only holds ignorePatterns: external URLs and mailto, which a firewall
# or a rate limit turns into a false failure, and docker-compose.override.yml,
# which every developer creates locally and git ignores.
markdown-link-check --config "$GIT_ROOT/.markdown-link-check.json" $MARKDOWN_FILES

# Not mandatory yet and too verbose
# cspell lint "$GIT_ROOT" --gitignore -c "$GIT_ROOT/.cspell.json"
