---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: fullstack-rust-react-template
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres-exporter
